@startuml
'https://plantuml.com/sequence-diagram

autonumber

IDEA --> UTTPlugin : startup
UTTPlugin --> ProjectUttInitializer : collect all endpoints implementations
ProjectUttInitializer --> ProjectInfoService : get endpoint object
ProjectInfoService --> ProjectInfoService : save the instances
ProjectInfoService --> UTTPlugin

@enduml